language: php
dist: precise
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer update
script:
  - vendor/bin/phpunit
