language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
git:
  submodules: false
before_script:
  - git submodule update --init
  - composer self-update
  - composer update
script:
  - ./vendor/bin/phpunit
