language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
git:
  submodules: false
before_script:
  - mysql -e 'CREATE DATABASE bear_demo;'
  - composer self-update
  - composer update
  - mysql -uroot < vendor/bearsaturday/demo.local/data/entries.sql
script:
  - ./vendor/bin/phpunit
